---
- hosts: acme
  gather_facts: false
  
  vars_files: 
  - group_vars/passwords

  tasks:
  - name: get all config
    raw: show running
    register: show_run

  - name: dump to file
    local_action: copy content="{{ show_run.stdout }}" dest=./files/{{ inventory_hostname }}.original
