---

- hosts: legacy
  gather_facts: false
  connection: local
  vars_files: 
  - group_vars/passwords
  
  roles:
    - non-standard
    - management

- hosts: routers
  gather_facts: false
  connection: local
  roles:
    - wan-qos
    - routing
  tags:
    - test

- hosts: switches
  gather_facts: false
  connection: local
 
  roles:
    - access-ports
    - vlans
